config/routes.rb
BHCC::Application.routes.draw do

  resources :ride_data

  resources :bhcc_accesses

  root :to => 'bhcc_accesses#index'
  get 'bhcc/home'
  get 'bhcc/leaderboard'
  get 'bhcc/May2013'
  get 'bhcc/June2013'
  get 'bhcc/getLastRide'
  get 'bhcc/testMethod'

end

app/controllers/bhcc_accesses_controller.rb
class BhccAccessesController < ApplicationController
  # GET /bhcc_accesses
  # GET /bhcc_accesses.json
  def index


    myParams = params[:code] 

    response = HTTParty.post("https://www.strava.com/oauth/token",
      :query => { :client_id => "177", :client_secret=> "ef771e84b333761f8cdf75b70be82aa396862e5e",:code => params[:code] })


    access_token = response["access_token"]

    @at = access_token

  if (access_token != nil)

   if BhccAccess.exists?(:token => access_token)

      puts "This token is already registered"

    else
    
    url = "https://www.strava.com/api/v3/athlete?access_token=#{access_token}"
    user_response = HTTParty.get url,:format  =>"json"

    user = JSON.parse(user_response)

    firstname = user["firstname"]
    lastname = user["lastname"]
    fullname = "#{firstname} #{lastname}"
    athlete_id = user["id"]


    # add access token to database
    token =BhccAccess.new do |t|

          t.token = access_token
          t.username = fullname
          t.userid = athlete_id

        end

        token.save
    
   end
 end

    @bhcc_accesses = BhccAccess.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bhcc_accesses }
    end
  end

  # GET /bhcc_accesses/1
  # GET /bhcc_accesses/1.json
  def show
    @bhcc_access = BhccAccess.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bhcc_access }
    end
  end

  # GET /bhcc_accesses/new
  # GET /bhcc_accesses/new.json
  def new
    @bhcc_access = BhccAccess.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bhcc_access }
    end
  end

  # GET /bhcc_accesses/1/edit
  def edit
    @bhcc_access = BhccAccess.find(params[:id])
  end

  # POST /bhcc_accesses
  # POST /bhcc_accesses.json
  def create
    @bhcc_access = BhccAccess.new(params[:bhcc_access])

    respond_to do |format|
      if @bhcc_access.save
        format.html { redirect_to @bhcc_access, notice: 'Bhcc access was successfully created.' }
        format.json { render json: @bhcc_access, status: :created, location: @bhcc_access }
      else
        format.html { render action: "new" }
        format.json { render json: @bhcc_access.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bhcc_accesses/1
  # PUT /bhcc_accesses/1.json
  def update
    @bhcc_access = BhccAccess.find(params[:id])

    respond_to do |format|
      if @bhcc_access.update_attributes(params[:bhcc_access])
        format.html { redirect_to @bhcc_access, notice: 'Bhcc access was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bhcc_access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bhcc_accesses/1
  # DELETE /bhcc_accesses/1.json
  def destroy
    @bhcc_access = BhccAccess.find(params[:id])
    @bhcc_access.destroy

    respond_to do |format|
      format.html { redirect_to bhcc_accesses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bhcc_accesses_helper.rb
module BhccAccessesHelper
end

app/views/bhcc_accesses/_form.html.erb
<%= form_for(@bhcc_access) do |f| %>
  <% if @bhcc_access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bhcc_access.errors.count, "error") %> prohibited this bhcc_access from being saved:</h2>

      <ul>
      <% @bhcc_access.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
    <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
      <div class="field">
    <%= f.label :userid %><br />
    <%= f.text_field :userid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= form_for @bhcc_access, :method => :delete do |f| %>   
  <%= f.label :username %><br />  
  <%= submit_tag "Delete Record" %> 
<% end %>

app/views/bhcc_accesses/edit.html.erb
<h1>Editing bhcc_access</h1>

<%= render 'form' %>

<%= link_to 'Show', @bhcc_access %> |
<%= link_to 'Back', bhcc_accesses_path %>

app/views/bhcc_accesses/index.html.erb
<div class = "row" style="display:table; margin:0 auto; padding-top:15px;">
	<div class="span10 well" style="width:742px; ">
<% if (@at == nil) %>
	<h1>Unauthorized</h1>
	<a href="http://www.bluehillscycling.com/BHCC-3/BHCC_strava.html">To Register Click here</a>
<% else %>
	

<h1>Welcome to the BHCC Strava Competions!</h1>
<h2>You are now registered!</h2>

</div>
<%end%>
</div>

app/views/bhcc_accesses/new.html.erb
<h1>New bhcc_access</h1>

<%= render 'form' %>

<%= link_to 'Back', bhcc_accesses_path %>

app/views/bhcc_accesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Token:</b>
  <%= @bhcc_access.token %>
</p>


<%= link_to 'Edit', edit_bhcc_access_path(@bhcc_access) %> |
<%= link_to 'Back', bhcc_accesses_path %>