config/routes.rb
BHCC::Application.routes.draw do

  resources :ride_data

  resources :bhcc_accesses

  root :to => 'bhcc_accesses#index'
  get 'bhcc/home'
  get 'bhcc/leaderboard'
  get 'bhcc/May2013'
  get 'bhcc/June2013'
  get 'bhcc/getLastRide'
  get 'bhcc/testMethod'

end

app/controllers/ride_data_controller.rb
class RideDataController < ApplicationController
  # GET /ride_data
  # GET /ride_data.json
  


  def checkifValid(floatTest)

    if(floatTest == nil)
      floatTest = 0.0
    end

    return floatTest

  end


  def index

   

    #get loop through rider credentials data base
    BhccAccess.find(:all).each do |token|

    url = "https://www.strava.com/api/v3/athlete/activities?access_token=#{token.token}"

    response = HTTParty.get url,:format  =>"json"
    
    ridedata = JSON.parse(response)

    ridedata.each do |ride|
    
    puts token.token
 
      if !RideDatum.exists?(:ride_id => String(ride["id"]))
           puts ride["id"]
          rides =RideDatum.new do |r|

            r.athlete_id = Integer(checkifValid(ride["athlete"]["id"]))  
            r.average_speed = Float(checkifValid(ride["average_speed"]))
            r.avg_power = Float(checkifValid(ride["average_power"]))
            r.calories = Float(checkifValid(ride["calories"]))
            r.location_city = ride["location_city"]
            r.max_power = Float(checkifValid(ride["max_power"]))
            r.max_speed = Float(checkifValid(ride["max_speed"]))
            r.moving_time = Float(checkifValid(ride["moving_time"]))
            r.ride_id = String(ride["id"])

        

            r.start_date =  ride["start_date_local"]  
            
            r.total_elevation_gain = ride["total_elevation_gain"]
            r.total_work = Float(checkifValid(ride["kilojoules"]))
            r.trainer = ride["trainer"]
            r.username = token.username
            r.distance = Float(checkifValid(ride["distance"]))
            
        end

        rides.save
      
      end
    end
    end


    @ride_data = RideDatum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ride_data }
    end
  end

  # GET /ride_data/1
  # GET /ride_data/1.json
  def show
    @ride_datum = RideDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ride_datum }
    end
  end

  # GET /ride_data/new
  # GET /ride_data/new.json
  def new
    @ride_datum = RideDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ride_datum }
    end
  end

  # GET /ride_data/1/edit
  def edit
    @ride_datum = RideDatum.find(params[:id])
  end

  # POST /ride_data
  # POST /ride_data.json
  def create
    @ride_datum = RideDatum.new(params[:ride_datum])

    respond_to do |format|
      if @ride_datum.save
        format.html { redirect_to @ride_datum, notice: 'Ride datum was successfully created.' }
        format.json { render json: @ride_datum, status: :created, location: @ride_datum }
      else
        format.html { render action: "new" }
        format.json { render json: @ride_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ride_data/1
  # PUT /ride_data/1.json
  def update
    @ride_datum = RideDatum.find(params[:id])

    respond_to do |format|
      if @ride_datum.update_attributes(params[:ride_datum])
        format.html { redirect_to @ride_datum, notice: 'Ride datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ride_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ride_data/1
  # DELETE /ride_data/1.json
  def destroy
    @ride_datum = RideDatum.find(params[:id])
    @ride_datum.destroy

    @ride_datum = RideDatum.delete_all

    respond_to do |format|
      format.html { redirect_to ride_data_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ride_data_helper.rb
module RideDataHelper
end

app/views/ride_data/_form.html.erb
<%= form_for(@ride_datum) do |f| %>
  <% if @ride_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ride_datum.errors.count, "error") %> prohibited this ride_datum from being saved:</h2>

      <ul>
      <% @ride_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ride_id %><br />
    <%= f.text_field :ride_id %>
  </div>
  <div class="field">
    <%= f.label :athlete_id %><br />
    <%= f.number_field :athlete_id %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :moving_time %><br />
    <%= f.text_field :moving_time %>
  </div>
  <div class="field">
    <%= f.label :total_elevation_gain %><br />
    <%= f.text_field :total_elevation_gain %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :location_city %><br />
    <%= f.text_field :location_city %>
  </div>
  <div class="field">
    <%= f.label :trainer %><br />
    <%= f.text_field :trainer %>
  </div>
  <div class="field">
    <%= f.label :average_speed %><br />
    <%= f.text_field :average_speed %>
  </div>
  <div class="field">
    <%= f.label :max_speed %><br />
    <%= f.text_field :max_speed %>
  </div>
  <div class="field">
    <%= f.label :calories %><br />
    <%= f.text_field :calories %>
  </div>
  <div class="field">
    <%= f.label :total_work %><br />
    <%= f.text_field :total_work %>
  </div>
  <div class="field">
    <%= f.label :max_power %><br />
    <%= f.text_field :max_power %>
  </div>
  <div class="field">
    <%= f.label :avg_power %><br />
    <%= f.text_field :avg_power %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ride_data/edit.html.erb
<h1>Editing ride_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @ride_datum %> |
<%= link_to 'Back', ride_data_path %>

app/views/ride_data/index.html.erb
<h1>Listing ride_data</h1>

<table>
  <tr>
    <th>Ride</th>
    <th>Athlete</th>
    <th>Distance</th>
    <th>Moving time</th>
    <th>Total elevation gain</th>
    <th>Start date</th>
    <th>Location city</th>
    <th>Trainer</th>
    <th>Average speed</th>
    <th>Max speed</th>
    <th>Calories</th>
    <th>Total work</th>
    <th>Max power</th>
    <th>Avg power</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ride_data.each do |ride_datum| %>
  <tr>
    <td><%= ride_datum.ride_id %></td>
    <td><%= ride_datum.athlete_id %></td>
    <td><%= ride_datum.distance %></td>
    <td><%= ride_datum.moving_time %></td>
    <td><%= ride_datum.total_elevation_gain %></td>
    <td><%= ride_datum.start_date %></td>
    <td><%= ride_datum.location_city %></td>
    <td><%= ride_datum.trainer %></td>
    <td><%= ride_datum.average_speed %></td>
    <td><%= ride_datum.max_speed %></td>
    <td><%= ride_datum.calories %></td>
    <td><%= ride_datum.total_work %></td>
    <td><%= ride_datum.max_power %></td>
    <td><%= ride_datum.avg_power %></td>
    <td><%= link_to 'Show', ride_datum %></td>
    <td><%= link_to 'Edit', edit_ride_datum_path(ride_datum) %></td>
    <td><%= link_to 'Destroy', ride_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ride datum', new_ride_datum_path %>

app/views/ride_data/new.html.erb
<h1>New ride_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', ride_data_path %>

app/views/ride_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ride:</b>
  <%= @ride_datum.ride_id %>
</p>

<p>
  <b>Athlete:</b>
  <%= @ride_datum.athlete_id %>
</p>

<p>
  <b>Distance:</b>
  <%= @ride_datum.distance %>
</p>

<p>
  <b>Moving time:</b>
  <%= @ride_datum.moving_time %>
</p>

<p>
  <b>Total elevation gain:</b>
  <%= @ride_datum.total_elevation_gain %>
</p>

<p>
  <b>Start date:</b>
  <%= @ride_datum.start_date %>
</p>

<p>
  <b>Location city:</b>
  <%= @ride_datum.location_city %>
</p>

<p>
  <b>Trainer:</b>
  <%= @ride_datum.trainer %>
</p>

<p>
  <b>Average speed:</b>
  <%= @ride_datum.average_speed %>
</p>

<p>
  <b>Max speed:</b>
  <%= @ride_datum.max_speed %>
</p>

<p>
  <b>Calories:</b>
  <%= @ride_datum.calories %>
</p>

<p>
  <b>Total work:</b>
  <%= @ride_datum.total_work %>
</p>

<p>
  <b>Max power:</b>
  <%= @ride_datum.max_power %>
</p>

<p>
  <b>Avg power:</b>
  <%= @ride_datum.avg_power %>
</p>


<%= link_to 'Edit', edit_ride_datum_path(@ride_datum) %> |
<%= link_to 'Back', ride_data_path %>